// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pdralrkymqjekzezfecw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBkcmFscmt5bXFqZWt6ZXpmZWN3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDc0MDgsImV4cCI6MjA2Mjg4MzQwOH0.rdr3Jplk-tGAQQQ-wWxEHZfbEqOWLiaVx2hh2pELOg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);